Tim Ryan
1000196736
hands on 4

SPECS Microsoft Windows OS, Lenovo x64-based laptop, Processor :Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s), Installed Physical Memory (RAM) 16.0 GB, Available Virtual Memory 11.4 GB I ran a Python3 kernel on jupyter notebook on google chrome browswer

In [1]:
def fib(n):
    if (n == 0):
        
        return 0
    if (n == 1):
        return 1
    return fib(n-1) + fib(n-2)

fib(0) = 0
fib(1) = 1

fib(5) needs to call fib(4) and fib(3) and then return their sum. The calling will traverse down the left [fib(n-1)] branch until it reaches fib(2) calling fib(1) and fib(0), at which point it will start returning values for the previous left-hand side of the level. The calls will then traverse down the right-hand side [fib(n-2)] in a similar manner, going down its leftmost branches and then returning when it reaches the bottom. Those right-hand values are then paired with their corresponding level's left-hand values and returned.

first, fib(5) is called. It calls fib(4) and fib(3) {Level 0}

fib(4) calls fib(3) and fib(2) {Level 1}

fib(3) calls fib(2) and fib(1)  {Level 2}

fib(2) calls fib(1) and fib(0). Their values of 1 and 0 are added and returned (1).  {Level 3}

Back on level 2, fib(3) has 1 for fib(2)'s value, it then pairs this with fib(1), gets 1, and returns the sum (2).

Back on level 1, fib(3) has returned 2, so now it fib(2) is called. It calls fib(1) and fib(0) and gets 1.
Level one now has values for fib(3) and fib(2), so it adds them and returns 3 back to level 0.

Back on level 0, fib(5) has received fib(4)'s value of 3. It now calls fib(3). 

fib(3) calls fib(2) and fib(1)  {back down a level}

fib(2) calls fib(1) and fib(0). Their values of 0 and 1 are added and returned (1).

Back up on the previous level, fib(3) has 1 for fib(2)'s value, it then pairs this with fib(1), gets 1, and returns the sum (2).

Finally back up to level 0, fib(5) has received returned values for fib(4) and fib(3). They are summed, and then 5 is returned.

In [2]:
fib(5)

5

In [3]:
def fibTime(n): 
    print("on level fib n = ", n)
    if (n == 0):
        print("returning 0")
        return 0
    if (n == 1):          
        print("returning 1")
        return 1
    
    print("returning fib(s)")
    return fibTime(n-1) + fibTime(n-2)    # c3 ( for any of the returns ) + c4*2 for calls to fib

print(fibTime(5))

on level fib n =  5
returning fib(s)
on level fib n =  4
returning fib(s)
on level fib n =  3
returning fib(s)
on level fib n =  2
returning fib(s)
on level fib n =  1
returning 1
on level fib n =  0
returning 0
on level fib n =  1
returning 1
on level fib n =  2
returning fib(s)
on level fib n =  1
returning 1
on level fib n =  0
returning 0
on level fib n =  3
returning fib(s)
on level fib n =  2
returning fib(s)
on level fib n =  1
returning 1
on level fib n =  0
returning 0
on level fib n =  1
returning 1
5


Showing runtime and improvements to fib (for fun)

In [4]:
counter = 0
def fibTime(n): 
    global counter       
    counter += 1
    if (n == 0):            # c1
       # print("at 0      count is ", count, " n is: ", n)   
        return 0
    if (n == 1):          #  c2
       # print("at 1      count is ", count, " n is: ", n)
        return 1
   # print("still going count: ", count, " n is: ", n)
    return fibTime(n-1) + fibTime(n-2)    # c3 ( for any of the returns ) + c4*2 for calls to fib

print(fibTime(6))
print(counter)

8
25


In [5]:
counter = 0
print(fibTime(10))
print(counter)

55
177


In [6]:
counter = 0
print(fibTime(25))
print(counter)

75025
242785


As is shown above, the two if statements and the two fib recursive calls will happen whenever fib(0) and fib(1) are not returning. Fib(6) fib(10), and fib (25) have recursive counters of 2^4.5, 2^7.5, and 2^18, which are not far off from 2^n, which are in between the theta and omega cases of 2^n and 2^(n/2) which were proved in the hw.

To improve efficiency, I would have the previously called values of fib(x) stored in a lookup table of key-value pairs. This would save lots of calls to fib() that have previously been made and calculated.

In [7]:
import numpy as np


p = np.array([[1,3,5,7],[2,4,6,8],[0,9,10,11]])

def sortArrs(arr, k, n):
    final = []
    winner = -1
    mini = float('inf')
    print(arr)
    while len(arr) > 0:
        for a in range(0, k - 1):
            if arr[a][0] < mini:
                mini = arr[a][0]
                winner = a
                print("mini ", mini, " a  ", a , "winner ", winner )
        final.append(mini)
        print(final)
        arr = np.delete(arr, winner, 0)
        print(arr)
    return final

sortArrs(p, 4, 4)

[[ 1  3  5  7]
 [ 2  4  6  8]
 [ 0  9 10 11]]
mini  1  a   0 winner  0
mini  0  a   2 winner  2
[0]
[[1 3 5 7]
 [2 4 6 8]]


IndexError: index 2 is out of bounds for axis 0 with size 2

In [34]:
import numpy as np
import math

p = np.array([[1,3,5,7],[2,4,6,8],[0,9,10,11]])

def sortie(arr):
    final = []
    holder = arr.tolist()
    while holder:
        empty = 0
        mini = float('inf')
        winner = []
        for row in holder:
            if len(row) != 0:
                if row[0] < mini:
                    mini = row[0]
                    winner = row
            elif len(row) == 0:
                empty += 1
            if len(holder) == empty:
                myFinal = np.array(final)
                return final
        final.append(winner.pop(0))
    myFinal = np.array(final)
    return myFinal
            
print(sortie(p))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


I got stuck here for a while, because I was trying to find an efficient workaround for not being able to alter the shape of numpy arrays. Eventually I settled on converting the array into a list and then reconverting final back into an array. 
The time complexity is KN for the first conversion. Plus K accesses of the first element of the arrays for each length N of the arrays, potentially K times, so KKN. And then KN for the conversion back.
The runtime should be (more or less) K^2 * N. 

In [9]:
def removeDups(arr):
    seen = []
    for element in arr:
        if(arr[element] not in seen ):
            seen.append(arr[element])
    return seen
print (removeDups([1,1,2,2,3,4,5,5,6]))

[1, 2, 3, 4, 5]


Initially I fooled myself into thinking that this is linear runtime, because it just goes down the line and adds to the seen array if it's a new element. Of course, it has to look into seen[] each time it adds a new element...so

In [48]:
def remoDu2(arr):

    gooo = []     # c1
    j = 0         # c2
    if arr:       # c3
        gooo.append(arr[0])                       # c4
        for i in range(1, len(arr)):              # sigma n
            if arr[i] != gooo[j]:                 # nc5
                gooo.insert(j + 1, arr[i])        # nc6
                j += 1                            # nc7
        return gooo                               # c8

print (remoDu2([1,1,2,2,3,4,5,5,6]))


[1, 2, 3, 4, 5, 6]


Better time here. This keeps it linear (and simple) by just traversing the array and checking it's values vs the last unique value put into gooo. c1+c2+c3+c4+c8 + n(c5 + c6 + c7).
But, considering that python rewrites the whole array on each append, this isn't an accurate time complexity assessment, either. So...

In [102]:
def redu(arr):
    last = arr[len(arr) -1]
    i = 0
    while arr[i] != last:
        while arr[i] == arr[i+1]:
            arr.pop(i+1)
        i += 1
    length = len(arr) - i
    for p in range(1, length):
        arr.pop()
    return arr

print (redu([1,1,1.5,1.5,2,2,2,3,3,3,4,5,5,6,6,6]))

            

[1, 1.5, 2, 3, 4, 5, 6]


I think that this one is the best I can personally do at the moment. Although it has two nested whiles and a for loop, the pops keep it in place and it doesn't have to rehash previously visited indices. So it truly is linear.