Tim Ryan (1000196736) CSE 5311 
Hands on 11 

SPECS Microsoft Windows OS, Lenovo x64-based laptop, Processor :Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s), Installed Physical Memory (RAM) 16.0 GB, Available Virtual Memory 11.4 GB I ran a Python3 kernel on jupyter notebook on google chrome browswer.

In [1]:
import numpy as np


In [2]:
class Arr:
    def __init__(self, n):
        self.arr = np.zeros(n)
        self.cap = len(self.arr)
        self.size = 0
    def __str__(self):
        return str(self.arr)
    def ins(self, value):
        if(self.size < self.cap - 1):
            self.arr[self.size] = value
            self.size += 1
        else:
            a2 = np.zeros(self.cap)
            self.arr = np.append(self.arr, a2)
            self.cap = self.cap*2
            self.ins(value)

In [3]:
a = Arr(4)
print(a)
a.ins(1)
a.ins(2)
a.ins(3)
a.ins(4)
print(a)
a.ins(5)
print(a)

[0. 0. 0. 0.]
[1. 2. 3. 4. 0. 0. 0. 0.]
[1. 2. 3. 4. 5. 0. 0. 0.]


a) The cost of each insert is O(1)...except when the value size of the array meets its capacity
(which happens at n, then n*2, then n*3, etc.) the cost of inserts here are O(index).

the sum of costs (from i=0 to n) <= n + the sum of 2^j (from j=0 to floor(lg(n)))

which is                        < n + 2n
                                 = 3n
                                 which is O(n)
                                 
So for an initial array of size 4 with 8 inserts the cost would be:
1 + 1 + 1 + 4 + 1 + 1 + 1 + 8 = 18

Making each insert's amortized runtime be O(n)/n = O(1)


b) Initial bank = $0

normal insert actual = O(1) = 1, normal insert amortized = O(3) = 3

powers insert actual = O(n) = n, powers insert amortized = O(0) = 1

So inserting the first the numbers banks: 3($3) - 3($1)     =  $6

And inserting the fourth costs $0 - $4 which leaves the bank = $2

Elements 5 through 7 increases the bank to $2 + 3($3) - 3($1) =$8

And inserting at 8 takes it down 8 dollars, making the bank   = $0

Since the bank never reaches a non-negative value, the credit is good, and the assumptions hold.