Tim Ryan (1000196736) CSE 5311 
Hands on 11 

SPECS Microsoft Windows OS, Lenovo x64-based laptop, Processor :Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s), Installed Physical Memory (RAM) 16.0 GB, Available Virtual Memory 11.4 GB I ran a Python3 kernel on jupyter notebook on google chrome browswer.

In [1]:
import numpy as np


In [2]:
class Arr:
    def __init__(self, n):
        self.arr = np.zeros(n)
        self.cap = len(self.arr)
        self.size = 0
    def __str__(self):
        return str(self.arr)
    def ins(self, value):
        if(self.size < self.cap):
            self.arr[self.size] = value
            self.size += 1
        else:
            a2 = np.zeros(self.cap)
            self.arr = np.append(self.arr, a2)
            self.cap = self.cap*2
            print(self.arr)
            self.ins(value)

In [3]:
a = Arr(4)
print(a)
a.ins(1)
a.ins(2)
a.ins(3)
a.ins(4)
print(a)
a.ins(5)
print(a)

[0. 0. 0. 0.]
[1. 2. 3. 4.]
[1. 2. 3. 4. 0. 0. 0. 0.]
[1. 2. 3. 4. 5. 0. 0. 0.]
